name: ECS bvba
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99917
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9945186728145927
  lightness: 0.736219018464908
  saturation: 0.970521277980879
  rhythmicContrast: 0.5175850144587457
purpose: []
